### PR TITLE
Adds the Spreadsheets.tables([ranges]) that receives an array of sheets

### PR DESCRIPTION
**Pull request by cguedes**
@mderazon please give a look at this PR.

I've improved the response of `.table(...)` to include a hash by column name in the rows (see example bellow), and also the method `.tables(ranges)` that accepts and array with ranges and returns an array of table objects.

Note the use of `!A:ZZZ` in the test scenario. I don't know if we should "auto append" this in the lib to the calls without "!..." part in the sheet name. What do you think? 

| Header 1   | Header 2 | Header 3 |
| ---------- | -------- | -------- |
| row 1 text | $0.41    | 3.00     |
| ...        | ...      | ...      |

```javascript
const table = await gs.table('Formats')

{
 title: 'Formats',                                                        // name of the sheet/table
 headers: ['Header 1', 'Header 2', 'Header 3'],                           // name of the headers (1st row)
 formats: [                                                               // array with information regarding cell format
   { numberFormat: { type: 'NONE' } },
   { numberFormat: { type: 'CURRENCY', pattern: '"$"#,##0.00' } },
   { numberFormat: { type: 'NUMBER', pattern: '#,##0.00' } } ]
 rows: [                                                                  // rows contains the values for 2nd row ahead
   {                                                                      // Each row object has:
     cols: {                                                                  // cols - map header -> (value | stringValue)
       'Header 1': { value: 'row 1 text', stringValue: 'row 1 text' },
       'Header 2': { value: 0.41, stringValue: '$0.41' },
       'Header 3': { value: 3, stringValue: '3.00' }
      },
      values: ['row 1 text', 0.41, 3],                                        // values - array with values for each header
      stringValue: ['row 1 text', '$0.41', '3.00']                            // stringValue - string representation of the values for each header
    },
   { ... },
   { ... }
 ]
}
```

related with urbancups/node-sheets#5 and urbancups/node-sheets#7

### CODE REVIEW

**Comment by mderazon** [comment]
> Note the use of !A:ZZZ in the test scenario. I don't know if we should "auto append" this in the lib to the calls without "!..." part in the sheet name. What do you think?

I was thinking about it as well. I think that if we auto append it, then we should do #5 (split the table name from the range) and instruct people to make ranges without sheets names. Then we can do something ike
``` js
gs.tables[{sheet: 'main'}, {sheet: 'D001', range: 'A1:D3'}, {sheet: 'D002'}]
// return all of sheets 'main' and 'D002' and range 'A1:D3' of sheet 'D001'
// we will auto append A:ZZZ to sheets 'main' and 'D002'
```

But i'm on the fence if we should be doing it. On one hand, it's an end case and I don't know how common it is. On the other hand, when you fall into that case (sheets names are like cells) it feels like a bug and for me it wasn't intuitive to understand at all. Plus, I expect people to pull the entire sheet and not part of it most of the cases.

Hmmmmm......

**Comment by cguedes** [comment]
My only concern with this approach is that I will be a bit cumbersome to ask to only one sheet. Additionally, to receive the two type of arguments I've commented before, we can receive also a string that we will pass through to google sheets api. 

In the end, the options would be:

```js
const sheet = await gs.tables('main') // ranges = ['main']
const sheet = await gs.tables({sheet: 'main'}) // ranges = ['main!A:ZZZ']
const sheet = await gs.tables({sheet: 'main', range: 'A1:B4'}) // ranges = ['main!A1:B4']
const sheets = await gs.tables([{sheet: 'main'}, {sheet: 'D001', range: 'A1:D3'}, {sheet: 'D002'}]) // ranges = ['main!A:ZZZ', 'D001!A1:D3', 'D002!A:ZZZ']
```

The first three `sheet` returned values are objects, and the last `sheets` is an array of objects.

@mderazon what do you think?

**Comment by mderazon** [comment]
@cguedes 👍

**Comment by cguedes** [comment]
@mderazon I've implemented the changes, merged to master and a new NPM package version `0.3.0` is available with the changes.

**Pull request merged**
